#pragma once

#include <common.h>

CPP_WRAPPER(wii::base)

UNKNOWN_FUNCTION(PPCMfmsr);
UNKNOWN_FUNCTION(PPCMtmsr);
UNKNOWN_FUNCTION(PPCMfhid0);
UNKNOWN_FUNCTION(PPCMthid0);
UNKNOWN_FUNCTION(PPCMfl2cr);
UNKNOWN_FUNCTION(PPCMtl2cr);
UNKNOWN_FUNCTION(PPCMtdec);
UNKNOWN_FUNCTION(PPCSync);
UNKNOWN_FUNCTION(PPCHalt);
UNKNOWN_FUNCTION(PPCMtmmcr0);
UNKNOWN_FUNCTION(PPCMfmmcr1);
UNKNOWN_FUNCTION(PPCMtpmc1);
UNKNOWN_FUNCTION(PPCMtpmc2);
UNKNOWN_FUNCTION(PPCMtpmc3);
UNKNOWN_FUNCTION(PPCMtpmc4);
UNKNOWN_FUNCTION(PPCMffpscr);
UNKNOWN_FUNCTION(PPCMtfpscr);
UNKNOWN_FUNCTION(PPCMfhid2);
UNKNOWN_FUNCTION(PPCMthid2);
UNKNOWN_FUNCTION(PPCMfwpar);
UNKNOWN_FUNCTION(PPCMtwpar);
UNKNOWN_FUNCTION(PPCDisableSpeculation);
UNKNOWN_FUNCTION(PPCSetFpNonIEEEMode);
UNKNOWN_FUNCTION(PPCMthid4);

CPP_WRAPPER_END()
