#pragma once

#include <common.h>

CPP_WRAPPER(wii::sc)

UNKNOWN_FUNCTION(SCInit);
UNKNOWN_FUNCTION(SCCheckStatus);
UNKNOWN_FUNCTION(SCReloadConfFileAsync);
UNKNOWN_FUNCTION(OpenCallbackFromReload);
UNKNOWN_FUNCTION(ReadCallbackFromReload);
UNKNOWN_FUNCTION(CloseCallbackFromReload);
UNKNOWN_FUNCTION(FinishFromReload);
UNKNOWN_FUNCTION(CloseCallbackFromReloadError);
UNKNOWN_FUNCTION(ParseConfBuf);
UNKNOWN_FUNCTION(UnpackItem);
UNKNOWN_FUNCTION(DeleteItemByID);
UNKNOWN_FUNCTION(CreateItemByID);
UNKNOWN_FUNCTION(SCFindByteArrayItem);
UNKNOWN_FUNCTION(SCReplaceByteArrayItem);
UNKNOWN_FUNCTION(SCReplaceIntegerItem);
UNKNOWN_FUNCTION(SCFindU8Item);
UNKNOWN_FUNCTION(SCFindS8Item);
UNKNOWN_FUNCTION(SCFindU32Item);
UNKNOWN_FUNCTION(SCReplaceU8Item);
UNKNOWN_FUNCTION(__SCFlushSyncCallback);
UNKNOWN_FUNCTION(SCFlushAsync);
UNKNOWN_FUNCTION(MyNandCallback);
UNKNOWN_FUNCTION(SCGetAspectRatio);
UNKNOWN_FUNCTION(SCGetDisplayOffsetH);
UNKNOWN_FUNCTION(SCGetIdleMode);
UNKNOWN_FUNCTION(SCGetLanguage);
UNKNOWN_FUNCTION(SCGetProgressiveMode);
UNKNOWN_FUNCTION(SCGetScreenSaverMode);
UNKNOWN_FUNCTION(SCGetSoundMode);
UNKNOWN_FUNCTION(SCGetCounterBias);
UNKNOWN_FUNCTION(SCGetBtDeviceInfoArray);
UNKNOWN_FUNCTION(SCSetBtDeviceInfoArray);
UNKNOWN_FUNCTION(SCGetBtDpdSensibility);
UNKNOWN_FUNCTION(SCGetWpadMotorMode);
UNKNOWN_FUNCTION(SCSetWpadMotorMode);
UNKNOWN_FUNCTION(SCGetWpadSensorBarPosition);
UNKNOWN_FUNCTION(SCGetWpadSpeakerVolume);
UNKNOWN_FUNCTION(SCSetWpadSpeakerVolume);
UNKNOWN_FUNCTION(__SCF1);
UNKNOWN_FUNCTION(SCGetProductArea);

CPP_WRAPPER_END()
