/*
    Revolution SDK MTX library
*/

#pragma once

#include <common.h>
#include <wii/types.h>

UNKNOWN_FUNCTION(PSMTXIdentity);
UNKNOWN_FUNCTION(PSMTXConcat);
UNKNOWN_FUNCTION(PSMTXRotRad);
UNKNOWN_FUNCTION(PSMTXTrans);
UNKNOWN_FUNCTION(PSMTXTransApply);
UNKNOWN_FUNCTION(PSMTXScale);
UNKNOWN_FUNCTION(C_MTXLightOrtho);
UNKNOWN_FUNCTION(PSVECSubtract);
UNKNOWN_FUNCTION(PSVECScale);
UNKNOWN_FUNCTION(PSVECNormalize);
UNKNOWN_FUNCTION(PSVecSquareMag);
UNKNOWN_FUNCTION(PSVecMag);
UNKNOWN_FUNCTION(PSVECDotProduct);
UNKNOWN_FUNCTION(PSVECCrossProduct);
UNKNOWN_FUNCTION(C_MTXOrtho);
