#pragma once

#include <common.h>

UNKNOWN_FUNCTION(VISetPostRetraceCallback);
UNKNOWN_FUNCTION(VIInit);
UNKNOWN_FUNCTION(VIWaitForRetrace);
UNKNOWN_FUNCTION(VIFlush);
UNKNOWN_FUNCTION(VISetBlack);
UNKNOWN_FUNCTION(VIGetTvFormat);
UNKNOWN_FUNCTION(VIGetScanMode);
UNKNOWN_FUNCTION(VIGetDTVStatus);
UNKNOWN_FUNCTION(VISetVSyncTimingTest);
