#pragma once

#include <common.h>

CPP_WRAPPER(spm::charpixlitemwin)

UNKNOWN_FUNCTION(charPixlItemWinInit);
UNKNOWN_FUNCTION(charPixlItemWinReInit);
UNKNOWN_FUNCTION(charPixlItemWinOpen);
UNKNOWN_FUNCTION(func_80195e64);
bool charPixlItemWinIsClosed();
UNKNOWN_FUNCTION(charPixlItemWinGetNextWindow);
UNKNOWN_FUNCTION(func_80196004);
UNKNOWN_FUNCTION(initCharTab);
UNKNOWN_FUNCTION(func_80196174);
UNKNOWN_FUNCTION(func_801969dc);
UNKNOWN_FUNCTION(dispCharTab);
UNKNOWN_FUNCTION(deleteCharTab);
UNKNOWN_FUNCTION(initPixlTab);
UNKNOWN_FUNCTION(func_80196c8c);
UNKNOWN_FUNCTION(func_80197544);
UNKNOWN_FUNCTION(dispPixlTab);
UNKNOWN_FUNCTION(deletePixlTab);
UNKNOWN_FUNCTION(initItemTab);
UNKNOWN_FUNCTION(func_801976e8);
UNKNOWN_FUNCTION(func_80198238);
UNKNOWN_FUNCTION(dispItemTab);
UNKNOWN_FUNCTION(deleteItemTab);
UNKNOWN_FUNCTION(func_80198290);
UNKNOWN_FUNCTION(func_80198294);
UNKNOWN_FUNCTION(func_801982b4);
UNKNOWN_FUNCTION(func_801982c4);
UNKNOWN_FUNCTION(func_801984f4);
UNKNOWN_FUNCTION(func_80198874);
UNKNOWN_FUNCTION(dispTab);

CPP_WRAPPER_END()
