#pragma once

#include <common.h>

CPP_WRAPPER(spm::envdrv)

void envInit();
UNKNOWN_FUNCTION(envReInit);
UNKNOWN_FUNCTION(envCapture);
UNKNOWN_FUNCTION(envCapture2);
UNKNOWN_FUNCTION(envDisp);
void envMain();
UNKNOWN_FUNCTION(envDisp_Blur);
UNKNOWN_FUNCTION(envBlurOn);
UNKNOWN_FUNCTION(envBlurOff);
UNKNOWN_FUNCTION(func_80064014);
UNKNOWN_FUNCTION(func_800646b8);
UNKNOWN_FUNCTION(func_800646d8);
UNKNOWN_FUNCTION(func_800646d8);
UNKNOWN_FUNCTION(func_80064a5c);
UNKNOWN_FUNCTION(func_80064a68);
UNKNOWN_FUNCTION(func_80064af8);

CPP_WRAPPER_END()
